package http

import (
	"context"
	"net/http"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/tidefly-oss/tidefly-plane/internal/api/middleware"
	"github.com/tidefly-oss/tidefly-plane/internal/ca"
	"github.com/tidefly-oss/tidefly-plane/internal/models"
	"gorm.io/gorm"
)

type Handler struct {
	db        *gorm.DB
	caService *ca.Service
}

func New(db *gorm.DB, caService *ca.Service) *Handler {
	return &Handler{db: db, caService: caService}
}

func (h *Handler) RegisterRoutes(api huma.API, mw huma.Middlewares, adminMw huma.Middlewares) {
	// Public — no JWT, authenticated via registration token
	huma.Register(api, huma.Operation{
		OperationID: "agent-register",
		Method:      http.MethodPost,
		Path:        "/api/v1/agent/register",
		Summary:     "Register a worker agent",
		Tags:        []string{"Agent"},
	}, h.Register)

	// mTLS authenticated — worker renews its own cert
	huma.Register(api, huma.Operation{
		OperationID: "agent-renew-cert",
		Method:      http.MethodPost,
		Path:        "/api/v1/agent/renew",
		Summary:     "Renew worker mTLS certificate",
		Tags:        []string{"Agent"},
		Middlewares: mw,
	}, h.RenewCert)

	// Admin only
	huma.Register(api, huma.Operation{
		OperationID:   "agent-create-token",
		Method:        http.MethodPost,
		Path:          "/api/v1/agent/tokens",
		Summary:       "Create a worker registration token",
		Tags:          []string{"Agent"},
		DefaultStatus: http.StatusCreated,
		Middlewares:   adminMw,
	}, h.CreateToken)

	huma.Register(api, huma.Operation{
		OperationID: "agent-list-tokens",
		Method:      http.MethodGet,
		Path:        "/api/v1/agent/tokens",
		Summary:     "List registration tokens",
		Tags:        []string{"Agent"},
		Middlewares: adminMw,
	}, h.ListTokens)

	huma.Register(api, huma.Operation{
		OperationID: "agent-list-workers",
		Method:      http.MethodGet,
		Path:        "/api/v1/agent/workers",
		Summary:     "List registered worker nodes",
		Tags:        []string{"Agent"},
		Middlewares: mw,
	}, h.ListWorkers)

	huma.Register(api, huma.Operation{
		OperationID: "agent-revoke-worker",
		Method:      http.MethodDelete,
		Path:        "/api/v1/agent/workers/{id}",
		Summary:     "Revoke a worker node",
		Tags:        []string{"Agent"},
		Middlewares: adminMw,
	}, h.RevokeWorker)
}

// ── Register ──────────────────────────────────────────────────────────────────

type RegisterInput struct {
	Body struct {
		Token        string `json:"token" required:"true" doc:"One-time registration token"`
		WorkerID     string `json:"worker_id" required:"true" doc:"UUID generated by the agent"`
		Name         string `json:"name" required:"true" doc:"Human-readable server name, e.g. hetzner-fsn1-01"`
		Description  string `json:"description,omitempty"`
		AgentVersion string `json:"agent_version,omitempty"`
		OS           string `json:"os,omitempty"`
		Arch         string `json:"arch,omitempty"`
		RuntimeType  string `json:"runtime_type,omitempty"`
	}
}

type RegisterOutput struct {
	Body struct {
		WorkerID  string `json:"worker_id"`
		CertPEM   string `json:"cert_pem"`
		KeyPEM    string `json:"key_pem"`
		CACertPEM string `json:"ca_cert_pem"`
		ExpiresAt string `json:"expires_at"`
	}
}

func (h *Handler) Register(ctx context.Context, input *RegisterInput) (*RegisterOutput, error) {
	var existing models.WorkerNode
	if err := h.db.Where("id = ?", input.Body.WorkerID).First(&existing).Error; err == nil {
		return nil, huma.Error409Conflict("worker already registered")
	}

	token, err := h.caService.ConsumeRegistrationToken(input.Body.Token, input.Body.WorkerID)
	if err != nil {
		return nil, huma.Error401Unauthorized(err.Error())
	}

	issued, certPEM, keyPEM, err := h.caService.IssueWorkerCert(input.Body.WorkerID)
	if err != nil {
		return nil, huma.Error500InternalServerError("failed to issue certificate")
	}

	caCertPEM, err := h.caService.GetCACertPEM()
	if err != nil {
		return nil, huma.Error500InternalServerError("failed to retrieve CA cert")
	}

	worker := &models.WorkerNode{
		ID:                 input.Body.WorkerID,
		Name:               input.Body.Name,
		Description:        input.Body.Description,
		Status:             models.WorkerStatusPending,
		AgentVersion:       input.Body.AgentVersion,
		OS:                 input.Body.OS,
		Arch:               input.Body.Arch,
		RuntimeType:        input.Body.RuntimeType,
		RegisteredByUserID: token.CreatedByUserID,
	}
	if err := h.db.Create(worker).Error; err != nil {
		return nil, huma.Error500InternalServerError("failed to create worker record")
	}

	out := &RegisterOutput{}
	out.Body.WorkerID = input.Body.WorkerID
	out.Body.CertPEM = certPEM
	out.Body.KeyPEM = keyPEM
	out.Body.CACertPEM = caCertPEM
	out.Body.ExpiresAt = issued.NotAfter.Format(time.RFC3339)
	return out, nil
}

// ── RenewCert ─────────────────────────────────────────────────────────────────

type RenewCertInput struct {
	Body struct {
		WorkerID string `json:"worker_id" required:"true"`
	}
}

type RenewCertOutput struct {
	Body struct {
		CertPEM   string `json:"cert_pem"`
		KeyPEM    string `json:"key_pem"`
		CACertPEM string `json:"ca_cert_pem"`
		ExpiresAt string `json:"expires_at"`
	}
}

func (h *Handler) RenewCert(ctx context.Context, input *RenewCertInput) (*RenewCertOutput, error) {
	var worker models.WorkerNode
	if err := h.db.Where("id = ? AND status != ?", input.Body.WorkerID, models.WorkerStatusRevoked).
		First(&worker).Error; err != nil {
		return nil, huma.Error404NotFound("worker not found")
	}

	issued, certPEM, keyPEM, err := h.caService.IssueWorkerCert(input.Body.WorkerID)
	if err != nil {
		return nil, huma.Error500InternalServerError("failed to issue certificate")
	}

	caCertPEM, err := h.caService.GetCACertPEM()
	if err != nil {
		return nil, huma.Error500InternalServerError("failed to retrieve CA cert")
	}

	out := &RenewCertOutput{}
	out.Body.CertPEM = certPEM
	out.Body.KeyPEM = keyPEM
	out.Body.CACertPEM = caCertPEM
	out.Body.ExpiresAt = issued.NotAfter.Format(time.RFC3339)
	return out, nil
}

// ── CreateToken ───────────────────────────────────────────────────────────────

type CreateTokenInput struct {
	Body struct {
		Label string `json:"label,omitempty"`
	}
}

type CreateTokenOutput struct {
	Body struct {
		Token     string `json:"token"`
		ExpiresAt string `json:"expires_at"`
		Label     string `json:"label"`
	}
}

func (h *Handler) CreateToken(ctx context.Context, input *CreateTokenInput) (*CreateTokenOutput, error) {
	claims := middleware.UserFromHumaCtx(ctx)
	if claims == nil {
		return nil, huma.Error401Unauthorized("unauthorized")
	}

	token, err := h.caService.CreateRegistrationToken(claims.UserID, input.Body.Label)
	if err != nil {
		return nil, huma.Error500InternalServerError("failed to create token")
	}

	out := &CreateTokenOutput{}
	out.Body.Token = token.Token
	out.Body.ExpiresAt = token.ExpiresAt.Format(time.RFC3339)
	out.Body.Label = token.Label
	return out, nil
}

// ── ListTokens ────────────────────────────────────────────────────────────────

type ListTokensInput struct{}

type ListTokensOutput struct {
	Body []models.WorkerRegistrationToken
}

func (h *Handler) ListTokens(ctx context.Context, input *ListTokensInput) (*ListTokensOutput, error) {
	claims := middleware.UserFromHumaCtx(ctx)
	if claims == nil {
		return nil, huma.Error401Unauthorized("unauthorized")
	}

	tokens, err := h.caService.ListRegistrationTokens(claims.UserID)
	if err != nil {
		return nil, huma.Error500InternalServerError("failed to list tokens")
	}

	return &ListTokensOutput{Body: tokens}, nil
}

// ── ListWorkers ───────────────────────────────────────────────────────────────

type ListWorkersInput struct{}

type ListWorkersOutput struct {
	Body []models.WorkerNode
}

func (h *Handler) ListWorkers(ctx context.Context, input *ListWorkersInput) (*ListWorkersOutput, error) {
	var workers []models.WorkerNode
	if err := h.db.Order("created_at DESC").Find(&workers).Error; err != nil {
		return nil, huma.Error500InternalServerError("failed to list workers")
	}
	return &ListWorkersOutput{Body: workers}, nil
}

// ── RevokeWorker ──────────────────────────────────────────────────────────────

type RevokeWorkerInput struct {
	ID string `path:"id"`
}

type RevokeWorkerOutput struct{}

func (h *Handler) RevokeWorker(ctx context.Context, input *RevokeWorkerInput) (*RevokeWorkerOutput, error) {
	claims := middleware.UserFromHumaCtx(ctx)
	if claims == nil {
		return nil, huma.Error401Unauthorized("unauthorized")
	}

	if err := h.caService.RevokeWorkerCert(input.ID, claims.UserID); err != nil {
		return nil, huma.Error500InternalServerError("failed to revoke certificate")
	}

	if err := h.db.Model(&models.WorkerNode{}).
		Where("id = ?", input.ID).
		Update("status", models.WorkerStatusRevoked).Error; err != nil {
		return nil, huma.Error500InternalServerError("failed to revoke worker")
	}

	return &RevokeWorkerOutput{}, nil
}
