package http

import (
	"context"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/tidefly-oss/tidefly-plane/internal/api/middleware"
	"github.com/tidefly-oss/tidefly-plane/internal/ca"
	"github.com/tidefly-oss/tidefly-plane/internal/models"
	agentsvc "github.com/tidefly-oss/tidefly-plane/internal/services/agent"
	"gorm.io/gorm"
)

type Handler struct {
	db          *gorm.DB
	caService   *ca.Service
	agentClient *agentsvc.Client
}

func New(db *gorm.DB, caService *ca.Service, agentClient *agentsvc.Client) *Handler {
	return &Handler{db: db, caService: caService, agentClient: agentClient}
}

// ── Register ──────────────────────────────────────────────────────────────────

type RegisterInput struct {
	Body struct {
		Token        string `json:"token" required:"true" doc:"One-time registration token"`
		WorkerID     string `json:"worker_id" required:"true" doc:"UUID generated by the agent"`
		Name         string `json:"name" required:"true" doc:"Human-readable server name, e.g. hetzner-fsn1-01"`
		Description  string `json:"description,omitempty"`
		AgentVersion string `json:"agent_version,omitempty"`
		OS           string `json:"os,omitempty"`
		Arch         string `json:"arch,omitempty"`
		RuntimeType  string `json:"runtime_type,omitempty"`
	}
}

type RegisterOutput struct {
	Body struct {
		WorkerID  string `json:"worker_id"`
		CertPEM   string `json:"cert_pem"`
		KeyPEM    string `json:"key_pem"`
		CACertPEM string `json:"ca_cert_pem"`
		ExpiresAt string `json:"expires_at"`
	}
}

func (h *Handler) Register(_ context.Context, input *RegisterInput) (*RegisterOutput, error) {
	var existing models.WorkerNode
	if err := h.db.Where("id = ?", input.Body.WorkerID).First(&existing).Error; err == nil {
		return nil, huma.Error409Conflict("worker already registered")
	}

	token, err := h.caService.ConsumeRegistrationToken(input.Body.Token, input.Body.WorkerID)
	if err != nil {
		return nil, huma.Error401Unauthorized(err.Error())
	}

	issued, certPEM, keyPEM, err := h.caService.IssueWorkerCert(input.Body.WorkerID)
	if err != nil {
		return nil, huma.Error500InternalServerError("failed to issue certificate")
	}

	caCertPEM, err := h.caService.GetCACertPEM()
	if err != nil {
		return nil, huma.Error500InternalServerError("failed to retrieve CA cert")
	}

	worker := &models.WorkerNode{
		ID:                 input.Body.WorkerID,
		Name:               input.Body.Name,
		Description:        input.Body.Description,
		Status:             models.WorkerStatusPending,
		AgentVersion:       input.Body.AgentVersion,
		OS:                 input.Body.OS,
		Arch:               input.Body.Arch,
		RuntimeType:        input.Body.RuntimeType,
		RegisteredByUserID: token.CreatedByUserID,
	}
	if err := h.db.Create(worker).Error; err != nil {
		return nil, huma.Error500InternalServerError("failed to create worker record")
	}

	out := &RegisterOutput{}
	out.Body.WorkerID = input.Body.WorkerID
	out.Body.CertPEM = certPEM
	out.Body.KeyPEM = keyPEM
	out.Body.CACertPEM = caCertPEM
	out.Body.ExpiresAt = issued.NotAfter.Format(time.RFC3339)
	return out, nil
}

// ── RenewCert ─────────────────────────────────────────────────────────────────

type RenewCertInput struct {
	Body struct {
		WorkerID string `json:"worker_id" required:"true"`
	}
}

type RenewCertOutput struct {
	Body struct {
		CertPEM   string `json:"cert_pem"`
		KeyPEM    string `json:"key_pem"`
		CACertPEM string `json:"ca_cert_pem"`
		ExpiresAt string `json:"expires_at"`
	}
}

func (h *Handler) RenewCert(_ context.Context, input *RenewCertInput) (*RenewCertOutput, error) {
	var worker models.WorkerNode
	if err := h.db.Where("id = ? AND status != ?", input.Body.WorkerID, models.WorkerStatusRevoked).
		First(&worker).Error; err != nil {
		return nil, huma.Error404NotFound("worker not found")
	}

	issued, certPEM, keyPEM, err := h.caService.IssueWorkerCert(input.Body.WorkerID)
	if err != nil {
		return nil, huma.Error500InternalServerError("failed to issue certificate")
	}

	caCertPEM, err := h.caService.GetCACertPEM()
	if err != nil {
		return nil, huma.Error500InternalServerError("failed to retrieve CA cert")
	}

	out := &RenewCertOutput{}
	out.Body.CertPEM = certPEM
	out.Body.KeyPEM = keyPEM
	out.Body.CACertPEM = caCertPEM
	out.Body.ExpiresAt = issued.NotAfter.Format(time.RFC3339)
	return out, nil
}

// ── CreateToken ───────────────────────────────────────────────────────────────

type CreateTokenInput struct {
	Body struct {
		Label string `json:"label,omitempty"`
	}
}

type CreateTokenOutput struct {
	Body struct {
		Token     string `json:"token"`
		ExpiresAt string `json:"expires_at"`
		Label     string `json:"label"`
	}
}

func (h *Handler) CreateToken(ctx context.Context, input *CreateTokenInput) (*CreateTokenOutput, error) {
	claims := middleware.UserFromHumaCtx(ctx)
	if claims == nil {
		return nil, huma.Error401Unauthorized("unauthorized")
	}

	token, err := h.caService.CreateRegistrationToken(claims.UserID, input.Body.Label)
	if err != nil {
		return nil, huma.Error500InternalServerError("failed to create token")
	}

	out := &CreateTokenOutput{}
	out.Body.Token = token.Token
	out.Body.ExpiresAt = token.ExpiresAt.Format(time.RFC3339)
	out.Body.Label = token.Label
	return out, nil
}

// ── ListTokens ────────────────────────────────────────────────────────────────

type ListTokensInput struct{}

type ListTokensOutput struct {
	Body []models.WorkerRegistrationToken
}

func (h *Handler) ListTokens(ctx context.Context, _ *ListTokensInput) (*ListTokensOutput, error) {
	claims := middleware.UserFromHumaCtx(ctx)
	if claims == nil {
		return nil, huma.Error401Unauthorized("unauthorized")
	}

	tokens, err := h.caService.ListRegistrationTokens(claims.UserID)
	if err != nil {
		return nil, huma.Error500InternalServerError("failed to list tokens")
	}

	return &ListTokensOutput{Body: tokens}, nil
}

// ── ListWorkers ───────────────────────────────────────────────────────────────

type ListWorkersInput struct{}

type ListWorkersOutput struct {
	Body []models.WorkerNode
}

func (h *Handler) ListWorkers(_ context.Context, _ *ListWorkersInput) (*ListWorkersOutput, error) {
	var workers []models.WorkerNode
	if err := h.db.Order("created_at DESC").Find(&workers).Error; err != nil {
		return nil, huma.Error500InternalServerError("failed to list workers")
	}
	return &ListWorkersOutput{Body: workers}, nil
}

// ── RevokeWorker ──────────────────────────────────────────────────────────────

type RevokeWorkerInput struct {
	ID string `path:"id"`
}

type RevokeWorkerOutput struct{}

func (h *Handler) RevokeWorker(ctx context.Context, input *RevokeWorkerInput) (*RevokeWorkerOutput, error) {
	claims := middleware.UserFromHumaCtx(ctx)
	if claims == nil {
		return nil, huma.Error401Unauthorized("unauthorized")
	}

	if err := h.caService.RevokeWorkerCert(input.ID, claims.UserID); err != nil {
		return nil, huma.Error500InternalServerError("failed to revoke certificate")
	}

	if err := h.db.Model(&models.WorkerNode{}).
		Where("id = ?", input.ID).
		Update("status", models.WorkerStatusRevoked).Error; err != nil {
		return nil, huma.Error500InternalServerError("failed to revoke worker")
	}

	return &RevokeWorkerOutput{}, nil
}

// ── DeleteWorker ──────────────────────────────────────────────────────────────

type DeleteWorkerInput struct {
	ID string `path:"id"`
}

type DeleteWorkerOutput struct{}

func (h *Handler) DeleteWorker(ctx context.Context, input *DeleteWorkerInput) (*DeleteWorkerOutput, error) {
	claims := middleware.UserFromHumaCtx(ctx)
	if claims == nil {
		return nil, huma.Error401Unauthorized("unauthorized")
	}

	var worker models.WorkerNode
	if err := h.db.Where("id = ? AND status = ?", input.ID, models.WorkerStatusRevoked).
		First(&worker).Error; err != nil {
		return nil, huma.Error404NotFound("worker not found or not revoked")
	}

	if err := h.db.Delete(&worker).Error; err != nil {
		return nil, huma.Error500InternalServerError("failed to delete worker")
	}

	return &DeleteWorkerOutput{}, nil
}
