root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["set -a && source deploy/development/.env && set +a"]
cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ./cmd/tidefly"
entrypoint = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "internal/podman/generated"]
delay = 500
log = "tmp/build-errors.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
