package models

import (
	"time"

	"gorm.io/gorm"
)

// CertificateAuthority stores the Tidefly internal CA.
// There is exactly one row — the plane CA.
// CertPEM and KeyPEM are AES-256-GCM encrypted (base64).
type CertificateAuthority struct {
	ID        uint           `gorm:"primaryKey;autoIncrement" json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`

	// Encrypted PEM blobs (AES-256-GCM, base64)
	CertPEM string `gorm:"type:text;not null" json:"-"`
	KeyPEM  string `gorm:"type:text;not null" json:"-"`

	// Plaintext metadata
	Subject   string    `gorm:"type:varchar(255);not null" json:"subject"`
	NotBefore time.Time `gorm:"not null" json:"not_before"`
	NotAfter  time.Time `gorm:"not null" json:"not_after"`
	Serial    string    `gorm:"type:varchar(64);not null" json:"serial"`
}

func (CertificateAuthority) TableName() string { return "certificate_authorities" }

// IsExpiringSoon returns true if the CA expires within the given duration.
func (ca *CertificateAuthority) IsExpiringSoon(within time.Duration) bool {
	return time.Until(ca.NotAfter) < within
}

// ---

// IssuedCertificate tracks every cert the CA has signed.
// Used for revocation, renewal tracking and audit.
type IssuedCertificate struct {
	ID        uint           `gorm:"primaryKey;autoIncrement" json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`

	// Who owns this cert
	OwnerType string `gorm:"type:varchar(32);not null;index" json:"owner_type"` // "worker" | "plane"
	OwnerID   string `gorm:"type:varchar(64);not null;index" json:"owner_id"`   // worker UUID or "plane"

	// Encrypted PEM blobs
	CertPEM string `gorm:"type:text;not null" json:"-"`
	KeyPEM  string `gorm:"type:text;not null" json:"-"`

	// Plaintext metadata
	Subject   string    `gorm:"type:varchar(255);not null" json:"subject"`
	NotBefore time.Time `gorm:"not null" json:"not_before"`
	NotAfter  time.Time `gorm:"not null" json:"not_after"`
	Serial    string    `gorm:"type:varchar(64);not null;uniqueIndex" json:"serial"`

	// Lifecycle
	Revoked   bool       `gorm:"default:false;not null" json:"revoked"`
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	RevokedBy string     `gorm:"type:varchar(64)" json:"revoked_by,omitempty"`

	// Auto-renew tracking
	RenewedFromID *uint `gorm:"index" json:"renewed_from_id,omitempty"`
	RenewedToID   *uint `gorm:"index" json:"renewed_to_id,omitempty"`
}

func (IssuedCertificate) TableName() string { return "issued_certificates" }

func (c *IssuedCertificate) IsExpiringSoon(within time.Duration) bool {
	return !c.Revoked && time.Until(c.NotAfter) < within
}

func (c *IssuedCertificate) IsValid() bool {
	now := time.Now()
	return !c.Revoked && now.After(c.NotBefore) && now.Before(c.NotAfter)
}

// WorkerRegistrationToken is a one-time token generated by the Plane
// when a user clicks "Add Server". The Worker uses it once to register
// and receive its mTLS client certificate.
type WorkerRegistrationToken struct {
	ID        uint           `gorm:"primaryKey;autoIncrement" json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`

	// The token value shown to the user (e.g. tfy_reg_<random>)
	Token     string     `gorm:"type:varchar(128);not null;uniqueIndex" json:"token"`
	ExpiresAt time.Time  `gorm:"not null" json:"expires_at"`
	Used      bool       `gorm:"default:false;not null" json:"used"`
	UsedAt    *time.Time `json:"used_at,omitempty"`

	// Optional label so users know what this token was for
	Label string `gorm:"type:varchar(128)" json:"label"`

	// Set after use — links token to the worker that used it
	WorkerID *string `gorm:"type:varchar(64);index" json:"worker_id,omitempty"`

	// Who created this token (UUID string, matches auth.Claims.UserID)
	CreatedByUserID string `gorm:"type:varchar(64);not null" json:"created_by_user_id"`
}

func (WorkerRegistrationToken) TableName() string { return "worker_registration_tokens" }

func (t *WorkerRegistrationToken) IsValid() bool {
	return !t.Used && time.Now().Before(t.ExpiresAt)
}
