// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/tidefly-oss/tidefly-backend/internal/api"
)

// Injectors from wire.go:

// InitializeApp is the Wire entry point.
// Wire reads this file and generates wire_gen.go with the full wiring.
// Run: wire ./internal/bootstrap/
func InitializeApp() (*api.App, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup, err := ProvideLogger(config)
	if err != nil {
		return nil, nil, err
	}
	runtime, err := ProvideRuntime(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	db, cleanup2, err := ProvideDatabase(config, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, cleanup3, err := ProvideRedis(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authboss, err := ProvideAuthService(config, db, client)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	loader, err := ProvideTemplateLoader(config)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	service := ProvideNotificationsService(db)
	gitService := ProvideGitService(config)
	webhookService := ProvideWebhookService(config)
	server, cleanup4, err := ProvideJobServer(config, runtime, db, logger, service)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	asynqClient, cleanup5, err := ProvideAsynqClient(config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	notifierService := ProvideNotifierService(db, logger)
	app := api.NewApp(config, logger, runtime, db, authboss, loader, service, gitService, webhookService, server, asynqClient, notifierService)
	return app, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
