// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

// Injectors from wire.go:

// InitializeApp is the Wire entry point.
// Wire reads this file and generates wire_gen.go with the full wiring.
// Run: wire ./internal/bootstrap/
func InitializeApp() (*App, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup, err := ProvideLogger(config)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := ProvideDatabase(config, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	runtime, err := ProvideRuntime(config, db)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jwtService := ProvideJWTService(config)
	tokenStore := ProvideTokenStore(db)
	client := ProvideCaddyClient(config)
	loader := ProvideTemplateLoader()
	bus := ProvideEventBus()
	service := ProvideNotificationService(db, bus)
	gitService := ProvideGitService(config)
	webhookService := ProvideWebhookService(config)
	pool, cleanup3, err := ProvidePgxPool(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	notifier := ProvideNotifier(db, logger)
	registry := ProvideMetricsRegistry()
	adapter := ProvideCaddyIngress(client)
	caService, err := ProvideCAService(config, db)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server := ProvideAgentServer(config, db, caService)
	agentClient := ProvideAgentClient(server)
	reconciler := ProvideReconciler(db, runtime, adapter, service, logger)
	jobsServer, cleanup4, err := ProvideJobServer(config, pool, runtime, db, logger, service, notifier, registry, adapter, agentClient, reconciler, bus)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := NewApp(config, logger, runtime, db, jwtService, tokenStore, client, loader, service, gitService, webhookService, jobsServer, notifier, registry, caService, server, bus, adapter)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
