// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaneVersion  string                 `protobuf:"bytes,1,opt,name=plane_version,json=planeVersion,proto3" json:"plane_version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetPlaneVersion() string {
	if x != nil {
		return x.PlaneVersion
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AgentMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // UUID for correlation
	WorkerId  string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_CommandAck
	//	*AgentMessage_ContainerList
	//	*AgentMessage_ContainerLogs
	//	*AgentMessage_Metrics
	//	*AgentMessage_DeployResult
	//	*AgentMessage_Error
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentMessage) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *AgentHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

func (x *AgentMessage) GetContainerList() *ContainerListResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ContainerList); ok {
			return x.ContainerList
		}
	}
	return nil
}

func (x *AgentMessage) GetContainerLogs() *ContainerLogsResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ContainerLogs); ok {
			return x.ContainerLogs
		}
	}
	return nil
}

func (x *AgentMessage) GetMetrics() *MetricsResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *AgentMessage) GetDeployResult() *DeployResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_DeployResult); ok {
			return x.DeployResult
		}
	}
	return nil
}

func (x *AgentMessage) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *AgentHello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *AgentHeartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,12,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

type AgentMessage_ContainerList struct {
	ContainerList *ContainerListResult `protobuf:"bytes,13,opt,name=container_list,json=containerList,proto3,oneof"`
}

type AgentMessage_ContainerLogs struct {
	ContainerLogs *ContainerLogsResult `protobuf:"bytes,14,opt,name=container_logs,json=containerLogs,proto3,oneof"`
}

type AgentMessage_Metrics struct {
	Metrics *MetricsResult `protobuf:"bytes,15,opt,name=metrics,proto3,oneof"`
}

type AgentMessage_DeployResult struct {
	DeployResult *DeployResult `protobuf:"bytes,16,opt,name=deploy_result,json=deployResult,proto3,oneof"`
}

type AgentMessage_Error struct {
	Error *ErrorEvent `protobuf:"bytes,99,opt,name=error,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_CommandAck) isAgentMessage_Payload() {}

func (*AgentMessage_ContainerList) isAgentMessage_Payload() {}

func (*AgentMessage_ContainerLogs) isAgentMessage_Payload() {}

func (*AgentMessage_Metrics) isAgentMessage_Payload() {}

func (*AgentMessage_DeployResult) isAgentMessage_Payload() {}

func (*AgentMessage_Error) isAgentMessage_Payload() {}

// Sent once on connect — worker identifies itself and reports capabilities
type AgentHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	RuntimeType   string                 `protobuf:"bytes,4,opt,name=runtime_type,json=runtimeType,proto3" json:"runtime_type,omitempty"` // "docker" | "podman"
	Hostname      string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentHello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentHello) GetRuntimeType() string {
	if x != nil {
		return x.RuntimeType
	}
	return ""
}

func (x *AgentHello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// Sent every 30s to keep the stream alive and report basic status
type AgentHeartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix millis
	ContainerCount int32                  `protobuf:"varint,2,opt,name=container_count,json=containerCount,proto3" json:"container_count,omitempty"`
	CpuPercent     float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent     float64                `protobuf:"fixed64,4,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentHeartbeat) Reset() {
	*x = AgentHeartbeat{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeat) ProtoMessage() {}

func (x *AgentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentHeartbeat) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentHeartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentHeartbeat) GetContainerCount() int32 {
	if x != nil {
		return x.ContainerCount
	}
	return 0
}

func (x *AgentHeartbeat) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *AgentHeartbeat) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

// Acknowledgement for a plane command
type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // if not accepted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *CommandAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ContainerListResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Containers    []*Container           `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerListResult) Reset() {
	*x = ContainerListResult{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerListResult) ProtoMessage() {}

func (x *ContainerListResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerListResult.ProtoReflect.Descriptor instead.
func (*ContainerListResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerListResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ContainerListResult) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`      // running | exited | created ...
	Created       int64                  `protobuf:"varint,6,opt,name=created,proto3" json:"created,omitempty"` // unix millis
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ports         []*PortBinding         `protobuf:"bytes,8,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Container) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Container) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Container) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Container) GetPorts() []*PortBinding {
	if x != nil {
		return x.Ports
	}
	return nil
}

type PortBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostIp        string                 `protobuf:"bytes,1,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	HostPort      int32                  `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	ContainerPort int32                  `protobuf:"varint,3,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp | udp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortBinding) Reset() {
	*x = PortBinding{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortBinding) ProtoMessage() {}

func (x *PortBinding) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortBinding.ProtoReflect.Descriptor instead.
func (*PortBinding) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *PortBinding) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *PortBinding) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortBinding) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *PortBinding) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ContainerLogsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Line          string                 `protobuf:"bytes,3,opt,name=line,proto3" json:"line,omitempty"`
	IsStderr      bool                   `protobuf:"varint,4,opt,name=is_stderr,json=isStderr,proto3" json:"is_stderr,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerLogsResult) Reset() {
	*x = ContainerLogsResult{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerLogsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLogsResult) ProtoMessage() {}

func (x *ContainerLogsResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLogsResult.ProtoReflect.Descriptor instead.
func (*ContainerLogsResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ContainerLogsResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ContainerLogsResult) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerLogsResult) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *ContainerLogsResult) GetIsStderr() bool {
	if x != nil {
		return x.IsStderr
	}
	return false
}

func (x *ContainerLogsResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MetricsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemUsedMb     float64                `protobuf:"fixed64,3,opt,name=mem_used_mb,json=memUsedMb,proto3" json:"mem_used_mb,omitempty"`
	MemTotalMb    float64                `protobuf:"fixed64,4,opt,name=mem_total_mb,json=memTotalMb,proto3" json:"mem_total_mb,omitempty"`
	DiskUsedGb    float64                `protobuf:"fixed64,5,opt,name=disk_used_gb,json=diskUsedGb,proto3" json:"disk_used_gb,omitempty"`
	DiskTotalGb   float64                `protobuf:"fixed64,6,opt,name=disk_total_gb,json=diskTotalGb,proto3" json:"disk_total_gb,omitempty"`
	NetRxMb       float64                `protobuf:"fixed64,7,opt,name=net_rx_mb,json=netRxMb,proto3" json:"net_rx_mb,omitempty"`
	NetTxMb       float64                `protobuf:"fixed64,8,opt,name=net_tx_mb,json=netTxMb,proto3" json:"net_tx_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResult) Reset() {
	*x = MetricsResult{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResult) ProtoMessage() {}

func (x *MetricsResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResult.ProtoReflect.Descriptor instead.
func (*MetricsResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *MetricsResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *MetricsResult) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *MetricsResult) GetMemUsedMb() float64 {
	if x != nil {
		return x.MemUsedMb
	}
	return 0
}

func (x *MetricsResult) GetMemTotalMb() float64 {
	if x != nil {
		return x.MemTotalMb
	}
	return 0
}

func (x *MetricsResult) GetDiskUsedGb() float64 {
	if x != nil {
		return x.DiskUsedGb
	}
	return 0
}

func (x *MetricsResult) GetDiskTotalGb() float64 {
	if x != nil {
		return x.DiskTotalGb
	}
	return 0
}

func (x *MetricsResult) GetNetRxMb() float64 {
	if x != nil {
		return x.NetRxMb
	}
	return 0
}

func (x *MetricsResult) GetNetTxMb() float64 {
	if x != nil {
		return x.NetTxMb
	}
	return 0
}

type DeployResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ContainerId   string                 `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResult) Reset() {
	*x = DeployResult{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResult) ProtoMessage() {}

func (x *DeployResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResult.ProtoReflect.Descriptor instead.
func (*DeployResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DeployResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *DeployResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployResult) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DeployResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // empty if not related to a command
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorEvent) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ErrorEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PlaneMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // UUID — worker uses this in CommandAck
	WorkerId  string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PlaneMessage_ListContainers
	//	*PlaneMessage_StartContainer
	//	*PlaneMessage_StopContainer
	//	*PlaneMessage_RestartContainer
	//	*PlaneMessage_RemoveContainer
	//	*PlaneMessage_StreamLogs
	//	*PlaneMessage_Deploy
	//	*PlaneMessage_CollectMetrics
	//	*PlaneMessage_RegisterRoute
	//	*PlaneMessage_RemoveRoute
	//	*PlaneMessage_Ack
	Payload       isPlaneMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaneMessage) Reset() {
	*x = PlaneMessage{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaneMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaneMessage) ProtoMessage() {}

func (x *PlaneMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaneMessage.ProtoReflect.Descriptor instead.
func (*PlaneMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *PlaneMessage) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PlaneMessage) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *PlaneMessage) GetPayload() isPlaneMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PlaneMessage) GetListContainers() *CmdListContainers {
	if x != nil {
		if x, ok := x.Payload.(*PlaneMessage_ListContainers); ok {
			return x.ListContainers
		}
	}
	return nil
}

func (x *PlaneMessage) GetStartContainer() *CmdStartContainer {
	if x != nil {
		if x, ok := x.Payload.(*PlaneMessage_StartContainer); ok {
			return x.StartContainer
		}
	}
	return nil
}

func (x *PlaneMessage) GetStopContainer() *CmdStopContainer {
	if x != nil {
		if x, ok := x.Payload.(*PlaneMessage_StopContainer); ok {
			return x.StopContainer
		}
	}
	return nil
}

func (x *PlaneMessage) GetRestartContainer() *CmdRestartContainer {
	if x != nil {
		if x, ok := x.Payload.(*PlaneMessage_RestartContainer); ok {
			return x.RestartContainer
		}
	}
	return nil
}

func (x *PlaneMessage) GetRemoveContainer() *CmdRemoveContainer {
	if x != nil {
		if x, ok := x.Payload.(*PlaneMessage_RemoveContainer); ok {
			return x.RemoveContainer
		}
	}
	return nil
}

func (x *PlaneMessage) GetStreamLogs() *CmdStreamLogs {
	if x != nil {
		if x, ok := x.Payload.(*PlaneMessage_StreamLogs); ok {
			return x.StreamLogs
		}
	}
	return nil
}

func (x *PlaneMessage) GetDeploy() *CmdDeploy {
	if x != nil {
		if x, ok := x.Payload.(*PlaneMessage_Deploy); ok {
			return x.Deploy
		}
	}
	return nil
}

func (x *PlaneMessage) GetCollectMetrics() *CmdCollectMetrics {
	if x != nil {
		if x, ok := x.Payload.(*PlaneMessage_CollectMetrics); ok {
			return x.CollectMetrics
		}
	}
	return nil
}

func (x *PlaneMessage) GetRegisterRoute() *CmdRegisterRoute {
	if x != nil {
		if x, ok := x.Payload.(*PlaneMessage_RegisterRoute); ok {
			return x.RegisterRoute
		}
	}
	return nil
}

func (x *PlaneMessage) GetRemoveRoute() *CmdRemoveRoute {
	if x != nil {
		if x, ok := x.Payload.(*PlaneMessage_RemoveRoute); ok {
			return x.RemoveRoute
		}
	}
	return nil
}

func (x *PlaneMessage) GetAck() *PlaneAck {
	if x != nil {
		if x, ok := x.Payload.(*PlaneMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isPlaneMessage_Payload interface {
	isPlaneMessage_Payload()
}

type PlaneMessage_ListContainers struct {
	ListContainers *CmdListContainers `protobuf:"bytes,10,opt,name=list_containers,json=listContainers,proto3,oneof"`
}

type PlaneMessage_StartContainer struct {
	StartContainer *CmdStartContainer `protobuf:"bytes,11,opt,name=start_container,json=startContainer,proto3,oneof"`
}

type PlaneMessage_StopContainer struct {
	StopContainer *CmdStopContainer `protobuf:"bytes,12,opt,name=stop_container,json=stopContainer,proto3,oneof"`
}

type PlaneMessage_RestartContainer struct {
	RestartContainer *CmdRestartContainer `protobuf:"bytes,13,opt,name=restart_container,json=restartContainer,proto3,oneof"`
}

type PlaneMessage_RemoveContainer struct {
	RemoveContainer *CmdRemoveContainer `protobuf:"bytes,14,opt,name=remove_container,json=removeContainer,proto3,oneof"`
}

type PlaneMessage_StreamLogs struct {
	StreamLogs *CmdStreamLogs `protobuf:"bytes,15,opt,name=stream_logs,json=streamLogs,proto3,oneof"`
}

type PlaneMessage_Deploy struct {
	Deploy *CmdDeploy `protobuf:"bytes,16,opt,name=deploy,proto3,oneof"`
}

type PlaneMessage_CollectMetrics struct {
	CollectMetrics *CmdCollectMetrics `protobuf:"bytes,17,opt,name=collect_metrics,json=collectMetrics,proto3,oneof"`
}

type PlaneMessage_RegisterRoute struct {
	RegisterRoute *CmdRegisterRoute `protobuf:"bytes,18,opt,name=register_route,json=registerRoute,proto3,oneof"`
}

type PlaneMessage_RemoveRoute struct {
	RemoveRoute *CmdRemoveRoute `protobuf:"bytes,19,opt,name=remove_route,json=removeRoute,proto3,oneof"`
}

type PlaneMessage_Ack struct {
	Ack *PlaneAck `protobuf:"bytes,99,opt,name=ack,proto3,oneof"`
}

func (*PlaneMessage_ListContainers) isPlaneMessage_Payload() {}

func (*PlaneMessage_StartContainer) isPlaneMessage_Payload() {}

func (*PlaneMessage_StopContainer) isPlaneMessage_Payload() {}

func (*PlaneMessage_RestartContainer) isPlaneMessage_Payload() {}

func (*PlaneMessage_RemoveContainer) isPlaneMessage_Payload() {}

func (*PlaneMessage_StreamLogs) isPlaneMessage_Payload() {}

func (*PlaneMessage_Deploy) isPlaneMessage_Payload() {}

func (*PlaneMessage_CollectMetrics) isPlaneMessage_Payload() {}

func (*PlaneMessage_RegisterRoute) isPlaneMessage_Payload() {}

func (*PlaneMessage_RemoveRoute) isPlaneMessage_Payload() {}

func (*PlaneMessage_Ack) isPlaneMessage_Payload() {}

type CmdListContainers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdListContainers) Reset() {
	*x = CmdListContainers{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdListContainers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdListContainers) ProtoMessage() {}

func (x *CmdListContainers) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdListContainers.ProtoReflect.Descriptor instead.
func (*CmdListContainers) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

type CmdStartContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdStartContainer) Reset() {
	*x = CmdStartContainer{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdStartContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdStartContainer) ProtoMessage() {}

func (x *CmdStartContainer) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdStartContainer.ProtoReflect.Descriptor instead.
func (*CmdStartContainer) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *CmdStartContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type CmdStopContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	TimeoutSec    int32                  `protobuf:"varint,2,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdStopContainer) Reset() {
	*x = CmdStopContainer{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdStopContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdStopContainer) ProtoMessage() {}

func (x *CmdStopContainer) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdStopContainer.ProtoReflect.Descriptor instead.
func (*CmdStopContainer) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CmdStopContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CmdStopContainer) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

type CmdRestartContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdRestartContainer) Reset() {
	*x = CmdRestartContainer{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdRestartContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdRestartContainer) ProtoMessage() {}

func (x *CmdRestartContainer) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdRestartContainer.ProtoReflect.Descriptor instead.
func (*CmdRestartContainer) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *CmdRestartContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type CmdRemoveContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdRemoveContainer) Reset() {
	*x = CmdRemoveContainer{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdRemoveContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdRemoveContainer) ProtoMessage() {}

func (x *CmdRemoveContainer) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdRemoveContainer.ProtoReflect.Descriptor instead.
func (*CmdRemoveContainer) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *CmdRemoveContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CmdRemoveContainer) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type CmdStreamLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	TailLines     int32                  `protobuf:"varint,3,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdStreamLogs) Reset() {
	*x = CmdStreamLogs{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdStreamLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdStreamLogs) ProtoMessage() {}

func (x *CmdStreamLogs) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdStreamLogs.ProtoReflect.Descriptor instead.
func (*CmdStreamLogs) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *CmdStreamLogs) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CmdStreamLogs) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *CmdStreamLogs) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

type CmdDeploy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"` // KEY=VALUE
	Ports         []*PortSpec            `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limits        *ResourceLimits        `protobuf:"bytes,7,opt,name=limits,proto3" json:"limits,omitempty"`
	Volumes       []*VolumeMount         `protobuf:"bytes,8,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Network       string                 `protobuf:"bytes,9,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdDeploy) Reset() {
	*x = CmdDeploy{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdDeploy) ProtoMessage() {}

func (x *CmdDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdDeploy.ProtoReflect.Descriptor instead.
func (*CmdDeploy) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *CmdDeploy) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CmdDeploy) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CmdDeploy) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CmdDeploy) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CmdDeploy) GetPorts() []*PortSpec {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *CmdDeploy) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CmdDeploy) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *CmdDeploy) GetVolumes() []*VolumeMount {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *CmdDeploy) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type PortSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerPort int32                  `protobuf:"varint,1,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	HostPort      int32                  `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortSpec) Reset() {
	*x = PortSpec{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortSpec) ProtoMessage() {}

func (x *PortSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortSpec.ProtoReflect.Descriptor instead.
func (*PortSpec) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *PortSpec) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *PortSpec) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortSpec) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryBytes   int64                  `protobuf:"varint,1,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	CpuShares     float64                `protobuf:"fixed64,2,opt,name=cpu_shares,json=cpuShares,proto3" json:"cpu_shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *ResourceLimits) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceLimits) GetCpuShares() float64 {
	if x != nil {
		return x.CpuShares
	}
	return 0
}

type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *VolumeMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *VolumeMount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *VolumeMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type CmdCollectMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdCollectMetrics) Reset() {
	*x = CmdCollectMetrics{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdCollectMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdCollectMetrics) ProtoMessage() {}

func (x *CmdCollectMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdCollectMetrics.ProtoReflect.Descriptor instead.
func (*CmdCollectMetrics) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

type CmdRegisterRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upstream      string                 `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"` // container:port
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Tls           bool                   `protobuf:"varint,3,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdRegisterRoute) Reset() {
	*x = CmdRegisterRoute{}
	mi := &file_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdRegisterRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdRegisterRoute) ProtoMessage() {}

func (x *CmdRegisterRoute) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdRegisterRoute.ProtoReflect.Descriptor instead.
func (*CmdRegisterRoute) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{25}
}

func (x *CmdRegisterRoute) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *CmdRegisterRoute) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CmdRegisterRoute) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

type CmdRemoveRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdRemoveRoute) Reset() {
	*x = CmdRemoveRoute{}
	mi := &file_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdRemoveRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdRemoveRoute) ProtoMessage() {}

func (x *CmdRemoveRoute) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdRemoveRoute.ProtoReflect.Descriptor instead.
func (*CmdRemoveRoute) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{26}
}

func (x *CmdRemoveRoute) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// Acknowledgement from Plane (e.g. after receiving AgentHello)
type PlaneAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaneAck) Reset() {
	*x = PlaneAck{}
	mi := &file_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaneAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaneAck) ProtoMessage() {}

func (x *PlaneAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaneAck.ProtoReflect.Descriptor instead.
func (*PlaneAck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{27}
}

func (x *PlaneAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PlaneAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\bagent.v1\"*\n" +
	"\vPingRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"Q\n" +
	"\fPingResponse\x12#\n" +
	"\rplane_version\x18\x01 \x01(\tR\fplaneVersion\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xa8\x04\n" +
	"\fAgentMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12,\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x14.agent.v1.AgentHelloH\x00R\x05hello\x128\n" +
	"\theartbeat\x18\v \x01(\v2\x18.agent.v1.AgentHeartbeatH\x00R\theartbeat\x127\n" +
	"\vcommand_ack\x18\f \x01(\v2\x14.agent.v1.CommandAckH\x00R\n" +
	"commandAck\x12F\n" +
	"\x0econtainer_list\x18\r \x01(\v2\x1d.agent.v1.ContainerListResultH\x00R\rcontainerList\x12F\n" +
	"\x0econtainer_logs\x18\x0e \x01(\v2\x1d.agent.v1.ContainerLogsResultH\x00R\rcontainerLogs\x123\n" +
	"\ametrics\x18\x0f \x01(\v2\x17.agent.v1.MetricsResultH\x00R\ametrics\x12=\n" +
	"\rdeploy_result\x18\x10 \x01(\v2\x16.agent.v1.DeployResultH\x00R\fdeployResult\x12,\n" +
	"\x05error\x18c \x01(\v2\x14.agent.v1.ErrorEventH\x00R\x05errorB\t\n" +
	"\apayload\"\x94\x01\n" +
	"\n" +
	"AgentHello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12!\n" +
	"\fruntime_type\x18\x04 \x01(\tR\vruntimeType\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\"\x99\x01\n" +
	"\x0eAgentHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12'\n" +
	"\x0fcontainer_count\x18\x02 \x01(\x05R\x0econtainerCount\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x04 \x01(\x01R\n" +
	"memPercent\"_\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"i\n" +
	"\x13ContainerListResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x123\n" +
	"\n" +
	"containers\x18\x02 \x03(\v2\x13.agent.v1.ContainerR\n" +
	"containers\"\xae\x02\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x18\n" +
	"\acreated\x18\x06 \x01(\x03R\acreated\x127\n" +
	"\x06labels\x18\a \x03(\v2\x1f.agent.v1.Container.LabelsEntryR\x06labels\x12+\n" +
	"\x05ports\x18\b \x03(\v2\x15.agent.v1.PortBindingR\x05ports\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\vPortBinding\x12\x17\n" +
	"\ahost_ip\x18\x01 \x01(\tR\x06hostIp\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\x05R\bhostPort\x12%\n" +
	"\x0econtainer_port\x18\x03 \x01(\x05R\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\"\xa6\x01\n" +
	"\x13ContainerLogsResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04line\x18\x03 \x01(\tR\x04line\x12\x1b\n" +
	"\tis_stderr\x18\x04 \x01(\bR\bisStderr\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x8f\x02\n" +
	"\rMetricsResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12\x1e\n" +
	"\vmem_used_mb\x18\x03 \x01(\x01R\tmemUsedMb\x12 \n" +
	"\fmem_total_mb\x18\x04 \x01(\x01R\n" +
	"memTotalMb\x12 \n" +
	"\fdisk_used_gb\x18\x05 \x01(\x01R\n" +
	"diskUsedGb\x12\"\n" +
	"\rdisk_total_gb\x18\x06 \x01(\x01R\vdiskTotalGb\x12\x1a\n" +
	"\tnet_rx_mb\x18\a \x01(\x01R\anetRxMb\x12\x1a\n" +
	"\tnet_tx_mb\x18\b \x01(\x01R\anetTxMb\"\x80\x01\n" +
	"\fDeployResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"Y\n" +
	"\n" +
	"ErrorEvent\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa2\x06\n" +
	"\fPlaneMessage\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12F\n" +
	"\x0flist_containers\x18\n" +
	" \x01(\v2\x1b.agent.v1.CmdListContainersH\x00R\x0elistContainers\x12F\n" +
	"\x0fstart_container\x18\v \x01(\v2\x1b.agent.v1.CmdStartContainerH\x00R\x0estartContainer\x12C\n" +
	"\x0estop_container\x18\f \x01(\v2\x1a.agent.v1.CmdStopContainerH\x00R\rstopContainer\x12L\n" +
	"\x11restart_container\x18\r \x01(\v2\x1d.agent.v1.CmdRestartContainerH\x00R\x10restartContainer\x12I\n" +
	"\x10remove_container\x18\x0e \x01(\v2\x1c.agent.v1.CmdRemoveContainerH\x00R\x0fremoveContainer\x12:\n" +
	"\vstream_logs\x18\x0f \x01(\v2\x17.agent.v1.CmdStreamLogsH\x00R\n" +
	"streamLogs\x12-\n" +
	"\x06deploy\x18\x10 \x01(\v2\x13.agent.v1.CmdDeployH\x00R\x06deploy\x12F\n" +
	"\x0fcollect_metrics\x18\x11 \x01(\v2\x1b.agent.v1.CmdCollectMetricsH\x00R\x0ecollectMetrics\x12C\n" +
	"\x0eregister_route\x18\x12 \x01(\v2\x1a.agent.v1.CmdRegisterRouteH\x00R\rregisterRoute\x12=\n" +
	"\fremove_route\x18\x13 \x01(\v2\x18.agent.v1.CmdRemoveRouteH\x00R\vremoveRoute\x12&\n" +
	"\x03ack\x18c \x01(\v2\x12.agent.v1.PlaneAckH\x00R\x03ackB\t\n" +
	"\apayload\"\x13\n" +
	"\x11CmdListContainers\"6\n" +
	"\x11CmdStartContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"V\n" +
	"\x10CmdStopContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1f\n" +
	"\vtimeout_sec\x18\x02 \x01(\x05R\n" +
	"timeoutSec\"8\n" +
	"\x13CmdRestartContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"M\n" +
	"\x12CmdRemoveContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"i\n" +
	"\rCmdStreamLogs\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x03 \x01(\x05R\ttailLines\"\x90\x03\n" +
	"\tCmdDeploy\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x10\n" +
	"\x03env\x18\x04 \x03(\tR\x03env\x12(\n" +
	"\x05ports\x18\x05 \x03(\v2\x12.agent.v1.PortSpecR\x05ports\x127\n" +
	"\x06labels\x18\x06 \x03(\v2\x1f.agent.v1.CmdDeploy.LabelsEntryR\x06labels\x120\n" +
	"\x06limits\x18\a \x01(\v2\x18.agent.v1.ResourceLimitsR\x06limits\x12/\n" +
	"\avolumes\x18\b \x03(\v2\x15.agent.v1.VolumeMountR\avolumes\x12\x18\n" +
	"\anetwork\x18\t \x01(\tR\anetwork\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\bPortSpec\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\x05R\rcontainerPort\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\x05R\bhostPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"R\n" +
	"\x0eResourceLimits\x12!\n" +
	"\fmemory_bytes\x18\x01 \x01(\x03R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"cpu_shares\x18\x02 \x01(\x01R\tcpuShares\"Z\n" +
	"\vVolumeMount\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\x13\n" +
	"\x11CmdCollectMetrics\"X\n" +
	"\x10CmdRegisterRoute\x12\x1a\n" +
	"\bupstream\x18\x01 \x01(\tR\bupstream\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x10\n" +
	"\x03tls\x18\x03 \x01(\bR\x03tls\"(\n" +
	"\x0eCmdRemoveRoute\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\">\n" +
	"\bPlaneAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\x84\x01\n" +
	"\fAgentService\x12=\n" +
	"\aConnect\x12\x16.agent.v1.AgentMessage\x1a\x16.agent.v1.PlaneMessage(\x010\x01\x125\n" +
	"\x04Ping\x12\x15.agent.v1.PingRequest\x1a\x16.agent.v1.PingResponseBJZHgithub.com/tidefly-oss/tidefly-plane/internal/api/v1/proto/agent;agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_agent_proto_goTypes = []any{
	(*PingRequest)(nil),         // 0: agent.v1.PingRequest
	(*PingResponse)(nil),        // 1: agent.v1.PingResponse
	(*AgentMessage)(nil),        // 2: agent.v1.AgentMessage
	(*AgentHello)(nil),          // 3: agent.v1.AgentHello
	(*AgentHeartbeat)(nil),      // 4: agent.v1.AgentHeartbeat
	(*CommandAck)(nil),          // 5: agent.v1.CommandAck
	(*ContainerListResult)(nil), // 6: agent.v1.ContainerListResult
	(*Container)(nil),           // 7: agent.v1.Container
	(*PortBinding)(nil),         // 8: agent.v1.PortBinding
	(*ContainerLogsResult)(nil), // 9: agent.v1.ContainerLogsResult
	(*MetricsResult)(nil),       // 10: agent.v1.MetricsResult
	(*DeployResult)(nil),        // 11: agent.v1.DeployResult
	(*ErrorEvent)(nil),          // 12: agent.v1.ErrorEvent
	(*PlaneMessage)(nil),        // 13: agent.v1.PlaneMessage
	(*CmdListContainers)(nil),   // 14: agent.v1.CmdListContainers
	(*CmdStartContainer)(nil),   // 15: agent.v1.CmdStartContainer
	(*CmdStopContainer)(nil),    // 16: agent.v1.CmdStopContainer
	(*CmdRestartContainer)(nil), // 17: agent.v1.CmdRestartContainer
	(*CmdRemoveContainer)(nil),  // 18: agent.v1.CmdRemoveContainer
	(*CmdStreamLogs)(nil),       // 19: agent.v1.CmdStreamLogs
	(*CmdDeploy)(nil),           // 20: agent.v1.CmdDeploy
	(*PortSpec)(nil),            // 21: agent.v1.PortSpec
	(*ResourceLimits)(nil),      // 22: agent.v1.ResourceLimits
	(*VolumeMount)(nil),         // 23: agent.v1.VolumeMount
	(*CmdCollectMetrics)(nil),   // 24: agent.v1.CmdCollectMetrics
	(*CmdRegisterRoute)(nil),    // 25: agent.v1.CmdRegisterRoute
	(*CmdRemoveRoute)(nil),      // 26: agent.v1.CmdRemoveRoute
	(*PlaneAck)(nil),            // 27: agent.v1.PlaneAck
	nil,                         // 28: agent.v1.Container.LabelsEntry
	nil,                         // 29: agent.v1.CmdDeploy.LabelsEntry
}
var file_agent_proto_depIdxs = []int32{
	3,  // 0: agent.v1.AgentMessage.hello:type_name -> agent.v1.AgentHello
	4,  // 1: agent.v1.AgentMessage.heartbeat:type_name -> agent.v1.AgentHeartbeat
	5,  // 2: agent.v1.AgentMessage.command_ack:type_name -> agent.v1.CommandAck
	6,  // 3: agent.v1.AgentMessage.container_list:type_name -> agent.v1.ContainerListResult
	9,  // 4: agent.v1.AgentMessage.container_logs:type_name -> agent.v1.ContainerLogsResult
	10, // 5: agent.v1.AgentMessage.metrics:type_name -> agent.v1.MetricsResult
	11, // 6: agent.v1.AgentMessage.deploy_result:type_name -> agent.v1.DeployResult
	12, // 7: agent.v1.AgentMessage.error:type_name -> agent.v1.ErrorEvent
	7,  // 8: agent.v1.ContainerListResult.containers:type_name -> agent.v1.Container
	28, // 9: agent.v1.Container.labels:type_name -> agent.v1.Container.LabelsEntry
	8,  // 10: agent.v1.Container.ports:type_name -> agent.v1.PortBinding
	14, // 11: agent.v1.PlaneMessage.list_containers:type_name -> agent.v1.CmdListContainers
	15, // 12: agent.v1.PlaneMessage.start_container:type_name -> agent.v1.CmdStartContainer
	16, // 13: agent.v1.PlaneMessage.stop_container:type_name -> agent.v1.CmdStopContainer
	17, // 14: agent.v1.PlaneMessage.restart_container:type_name -> agent.v1.CmdRestartContainer
	18, // 15: agent.v1.PlaneMessage.remove_container:type_name -> agent.v1.CmdRemoveContainer
	19, // 16: agent.v1.PlaneMessage.stream_logs:type_name -> agent.v1.CmdStreamLogs
	20, // 17: agent.v1.PlaneMessage.deploy:type_name -> agent.v1.CmdDeploy
	24, // 18: agent.v1.PlaneMessage.collect_metrics:type_name -> agent.v1.CmdCollectMetrics
	25, // 19: agent.v1.PlaneMessage.register_route:type_name -> agent.v1.CmdRegisterRoute
	26, // 20: agent.v1.PlaneMessage.remove_route:type_name -> agent.v1.CmdRemoveRoute
	27, // 21: agent.v1.PlaneMessage.ack:type_name -> agent.v1.PlaneAck
	21, // 22: agent.v1.CmdDeploy.ports:type_name -> agent.v1.PortSpec
	29, // 23: agent.v1.CmdDeploy.labels:type_name -> agent.v1.CmdDeploy.LabelsEntry
	22, // 24: agent.v1.CmdDeploy.limits:type_name -> agent.v1.ResourceLimits
	23, // 25: agent.v1.CmdDeploy.volumes:type_name -> agent.v1.VolumeMount
	2,  // 26: agent.v1.AgentService.Connect:input_type -> agent.v1.AgentMessage
	0,  // 27: agent.v1.AgentService.Ping:input_type -> agent.v1.PingRequest
	13, // 28: agent.v1.AgentService.Connect:output_type -> agent.v1.PlaneMessage
	1,  // 29: agent.v1.AgentService.Ping:output_type -> agent.v1.PingResponse
	28, // [28:30] is the sub-list for method output_type
	26, // [26:28] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_CommandAck)(nil),
		(*AgentMessage_ContainerList)(nil),
		(*AgentMessage_ContainerLogs)(nil),
		(*AgentMessage_Metrics)(nil),
		(*AgentMessage_DeployResult)(nil),
		(*AgentMessage_Error)(nil),
	}
	file_agent_proto_msgTypes[13].OneofWrappers = []any{
		(*PlaneMessage_ListContainers)(nil),
		(*PlaneMessage_StartContainer)(nil),
		(*PlaneMessage_StopContainer)(nil),
		(*PlaneMessage_RestartContainer)(nil),
		(*PlaneMessage_RemoveContainer)(nil),
		(*PlaneMessage_StreamLogs)(nil),
		(*PlaneMessage_Deploy)(nil),
		(*PlaneMessage_CollectMetrics)(nil),
		(*PlaneMessage_RegisterRoute)(nil),
		(*PlaneMessage_RemoveRoute)(nil),
		(*PlaneMessage_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
