// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

// Injectors from wire.go:

// InitializeApp is the Wire entry point.
// Wire reads this file and generates wire_gen.go with the full wiring.
// Run: wire ./internal/bootstrap/
func InitializeApp() (*App, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup, err := ProvideLogger(config)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := ProvideDatabase(config, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	runtime, err := ProvideRuntime(config, db)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	service := ProvideJWTService(config)
	client, cleanup3, err := ProvideRedis(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tokenStore := ProvideTokenStore(client)
	caddyClient := ProvideCaddyClient(config)
	loader := ProvideTemplateLoader()
	bus := ProvideEventBus()
	notificationService := ProvideNotificationService(db, bus)
	gitService := ProvideGitService(config)
	webhookService := ProvideWebhookService(config)
	registry := ProvideMetricsRegistry()
	adapter := ProvideCaddyIngress(caddyClient)
	caService, err := ProvideCAService(config, db)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server := ProvideAgentServer(config, db, caService)
	agentClient := ProvideAgentClient(server)
	jobsServer, cleanup4, err := ProvideJobServer(config, runtime, db, logger, notificationService, registry, adapter, agentClient)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	asynqClient, cleanup5, err := ProvideAsynqClient(config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	notifier := ProvideNotifier(db, logger)
	app := NewApp(config, logger, runtime, db, service, tokenStore, caddyClient, loader, notificationService, gitService, webhookService, jobsServer, asynqClient, notifier, registry, caService, server, bus, adapter)
	return app, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
